version: '3'
services:
    db:
        container_name: "${PRODUCTION_NAME}_db"
        image: mysql:5.7
        ports:
            - "3306:30"
        volumes:
            - ./db/mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
    wordpress:
        container_name: "${PRODUCTION_NAME}_wp"
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - "${LOCAL_SERVER_PORT}:80"
        volumes:
            - ./wp-content:/var/www/html/wp-content
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
    phpmyadmin:
        container_name: "${PRODUCTION_NAME}_phpmyadmin"
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "${LOCAL_DB_PORT}:8080"
        depends_on:
            - db
    mailhog:
        image: mailhog/mailhog
        ports:
            - "${MAIL_LOCAL_PORT}:${MAIL_SMTP_PORT}"
