version: '3'
services:
    db:
        container_name: "${PRODUCTION_NAME}_db"
        image: mysql:5.7
        ports:
            - "3306:80"
        volumes:
            - ./db/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wp_db
            MYSQL_USER: wp_user
            MYSQL_PASSWORD: wp_pw
    wordpress:
        container_name: "${PRODUCTION_NAME}_wp"
        depends_on:
            - db
        image: wordpress:latest
        ports:
            - "${LOCAL_SERVER_PORT}:80"
        volumes:
            - ./wp:/var/www/html
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wp_db
            WORDPRESS_DB_PASSWORD: wp_pw
    phpmyadmin:
        container_name: "${PRODUCTION_NAME}_phpmyadmin"
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "${LOCAL_DB_PORT}:80"
        depends_on:
            - db
    mailhog:
        container_name: "${PRODUCTION_NAME}_mailhog"
        image: mailhog/mailhog:latest
        ports:
            - "${MAIL_LOCAL_PORT}:${MAIL_LOCAL_PORT}"
            - "${MAIL_SMTP_PORT}:${MAIL_SMTP_PORT}"
